project:
  type: website
  output-dir: docs

website:
  title: "This is me"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: project.qmd
        text: Project

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

