project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Project
      - href: hobby.qmd  # Add the reflection page here
        text: Hobby
      - href: Reflection.qmd  # Add the reflection page here
        text: Reflection


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

